### ISSUE TITLE
Keep getting a timeout error every time I try to start a recording

### ISSUE THREAD

**Issue by RavenHursT** [wulkano/Kap#1066] opened 2021-12-17 00:05 UTC
**macOS version:**
❯ sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
**Kap version:**
3.5.1 (3.5.1.1783)

#### Steps to reproduce
Open Kap, try to start a recording

#### Current behaviour
Recording doesn't start and after 5 seconds or so:
```
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
```

#### Expected behaviour
Should just work

**Comment by DNA643** [comment] 2021-12-17 03:44
+1

**Comment by SidKH** [comment] 2021-12-17 07:46
Downgrading to v3.4.2 solved it for me.
https://github.com/wulkano/Kap/issues/1063#issuecomment-996081377

**Comment by timothyis** [comment] 2021-12-23 11:41
Hi all, this seems to be a duplicate of #1063. I'll close this and we'll keep the conversation there. Thanks for the additional reports, however!

**Closed by timothyis** 2021-12-23 11:41 UTC
Labels: Type: Bug, Aperture
