### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by appleton** [wulkano/kap#582] opened 2018-10-09 09:32 UTC
**macOS version:** 10.13.6
**Kap version:** 3.0.0-beta.2

#### Steps to reproduce

1. Download the beta
2. Install by dragging to `/Applications`
3. Launch the app (via Alfred in case that's relevant)

#### Current behaviour

<img width="532" alt="screen shot 2018-10-09 at 10 31 21 am" src="https://user-images.githubusercontent.com/241576/46660222-7b689680-cbae-11e8-83c4-dedea5baa9cd.png">

#### Expected behaviour

For the app to start

#### Workaround

None afaict

**Comment by sindresorhus** [comment] 2018-10-09 09:58
Duplicate of #581

**Closed by sindresorhus** 2018-10-09 09:58 UTC
