### ISSUE TITLE
After Upgrading Kap Errors out on Kapture

### ISSUE THREAD

**Issue by bnb** [wulkano/kap#441] opened 2018-03-28 18:19 UTC
**Platform:** macOS
**Kap Version:** 2.1.1

### Steps to reproduce: 
- Upgrade from Kap 1.x to 2.1.1 via the upgrade notification
	- Restart is irrelevant. This happened both before and after restarting, though trying to kapture _before_ restarting may have made it permanent?
- Try to record a katpure
### Current behaviour:
Unexpectedly errors out whenever I try to kapture, then sends quite a few other errors once the initial error is dismissed.

![image](https://user-images.githubusercontent.com/502396/38048284-ea749b74-3292-11e8-9bca-5316838c9df8.png)

```
Unhandled Promise Rejection
Error: Call `.startRecording()` first
    at Aperture.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:141:13)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:205:39)
    at Generator.next (<anonymous>)
    at step (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:191)
    at file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:99)
    at EventEmitter.stopRecording (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:221:20)
```

**Comment by karaggeorge** [comment] 2018-03-29 13:18
That error was handled here: https://github.com/wulkano/kap/blob/master/app/src/renderer/js/main.js#L148-L163

So, my guess is that it's stuck on an old version. So for some reason, the update didn't work, but the version number was bumped to 2.1.1

**Comment by skllcrn** [comment] 2018-05-26 13:31
You're really good at finding weird errors @bnb 😂 Can you try again by updating to the latest Beta release or to Kap 2.1.2 if you haven't already?

**Comment by maxcell** [comment] 2018-06-29 02:17
Howdy! I actually have gotten this same error. In this version of Kap (2.1.1) and also in the latest (2.2.0). The only thing I have done is open up Kap and record. Once I attempt to stop a recording, I cannot escape the recording or even get a prompt about the rendering. 😦 I have really liked using Kap but unfortunately due to this, I cannot even make recordings.

```
Error: Call `.startRecording()` first
    at Aperture.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:141:13)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:202:39)
    at Generator.next (<anonymous>)
    at step (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:191)
    at file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:99)
    at EventEmitter.stopRecording (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:218:20)
```

**Comment by skllcrn** [comment] 2018-07-03 18:10
Would be great to at the very least identify a workaround for this... @bnb and @maxcell, could you try reinstalling Kap (including uninstalling all plugins and delete anything related to Kap in Application Support)?

**Comment by maxcell** [comment] 2018-07-03 21:51
@skllcrn I've managed to install the 3.0.0 and everything is working fine there though. 😄

**Comment by bnb** [comment] 2018-07-03 23:10
Had to do the same, seems to be working... though I had some similar(ish) errors off and on when I started IIRC. They resolved pretty quickly, though.

**Comment by mercxry** [comment] 2018-08-22 21:37
I have the same errors with and without plugins, installing the 3.0 didn't solved for me
![kap_error](https://user-images.githubusercontent.com/39272153/44492303-48049380-a664-11e8-9b9e-128808bd0dc4.png)

**Comment by pedromassango** [comment] 2018-09-18 12:05
Hey, I'm having the same error here.
With Version: **2.2.0**

`Unhandled Promise Rejection
Error: Call `.startRecording()` first
    at Aperture.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:141:13)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:207:39)
    at Generator.next (<anonymous>)
    at step (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:191)
    at file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:99)
    at EventEmitter.stopRecording (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:223:20)`

**Comment by skllcrn** [comment] 2018-09-18 12:36
The only workaround that seems to work in most cases is using the latest `[master](https://kap-artifacts.now.sh/master)` build @pedromassango, let me know if that works for you too!

**Comment by skllcrn** [comment] 2018-09-18 20:33
Use this link @pedromassango: [Download](https://kap-artifacts.now.sh/master). Once it's finished downloading, open it and follow the instructions to move it your your Applications folder. Once that's done you can open the app and hopefully use it without issues!

**Comment by pedromassango** [comment] 2018-09-22 08:15
Thank you

**Comment by sindresorhus** [comment] 2018-10-04 07:05
Did anyone manage to reproduce this with the latest Kap build?

**Comment by tkrotoff** [comment] 2019-01-20 11:31
I get this error with Kap 3.0.0 and 2.2.0 when trying to "gifify" a YouTube video: "Could not start recording within 5 seconds"

**Comment by skllcrn** [comment] 2019-02-22 20:05
Seems like we're talking about two different issues across several different builds of the app. I'll be closing this issue for now, if you're still seeing any of these issues on the [latest release](https://github.com/wulkano/kap/releases) please open a new issue.

**Closed by skllcrn** 2019-02-22 20:05 UTC
Labels: Can't Reproduce, Help Wanted, Priority: High
