### ISSUE TITLE
Kap won't go away :(

### ISSUE THREAD

**Issue by callumacrae** [wulkano/kap#112] opened 2016-12-12 11:42 UTC
I have two monitors. When bringing my computer out of standby, Kap appeared, and now it won't go away:

<img width="459" alt="screen shot 2016-12-12 at 11 40 05" src="https://cloud.githubusercontent.com/assets/472830/21098184/d80a50c4-c05f-11e6-89b0-3e71fd55e22d.png">

If I bring it forward and then press the close button, it goes, but the next time I open kap, it doesn't go away.

It's not that I don't like kap, it's just I don't feel ready for this kind of relationship at this time.

I'm guessing it was caused by https://github.com/wulkano/kap/pull/93

**Comment by CodeTheory** [comment] 2016-12-12 11:44
Thanks for the report @callumacrae. We'll work on fixing this immediately. 😰

**Comment by callumacrae** [comment] 2016-12-12 11:44
thank you @CodeTheory, you are far quicker at replying to issues than @doot0

**Comment by matheuss** [comment] 2017-01-01 20:40
@callumacrae what do you mean by `it doesn't go away`? 🤔 When you detach the main window from the menubar, it'll behave like a standard macOS window – it'll not _vanish_ when it loses focus 😅

**Comment by callumacrae** [comment] 2017-01-03 09:47
Ah, I understand now: in that case, this is a different bug. I didn't detach it, it detached itself when my macbook came out of hibernate with a secondary monitor plugged in (but it only does this sometimes).

**Comment by CodeTheory** [comment] 2017-01-04 14:07
I think experience issues come from our upstream usage of `menubar`. We don't really control the behaviour it provides for us and could require some custom logic to be up to standards of a native app. Maybe we'll have to implement our own `menubar` as I think @matheuss wanted to do.

**Comment by skllcrn** [comment] 2017-11-01 16:17
This should be fixed on [`master`](https://kap-artifacts.now.sh/master), see also #188. Can you confirm @callumacrae?

**Comment by callumacrae** [comment] 2017-11-07 13:32
i am experiencing this with 1.0.1 still :(

**Comment by skllcrn** [comment] 2018-05-26 12:01
Related to #472

**Comment by star114** [comment] 2018-06-04 03:19
The problem is gone after mac os system upgrade to 10.13.5 in my case.
Are you guys still suffering the same problem?

**Comment by skllcrn** [comment] 2018-09-24 16:47
Closed via #494

**Closed by skllcrn** 2018-09-24 16:47 UTC
Labels: Can't Reproduce, Help Wanted, Priority: High, Type: Bug
