### ISSUE TITLE
Bothersome bug... I always get a piece of the KAP's recording window on my VIDEO...

### ISSUE THREAD

**Issue by inglesuniversal** [wulkano/kap#176] opened 2017-05-14 23:49 UTC
Hi:

I enjoy your script very much... but every time I record something with it on my Macbook Air... I get part of the recording window, this is for about 3 seconds once recording has been initiated, and this portion of your interface appears inside my chrome browser's top content which I record, so it looks like this... See picture... Please let me know how to fix this so it DOES NOT appear anymore. Thanks!

![screenshot 2017-05-14_18-41-31](https://cloud.githubusercontent.com/assets/15418158/26038781/a385b5fc-38d5-11e7-8048-afc723742216.png)

**Comment by hikerpig** [comment] 2017-05-16 06:25
You can click at the Kap menu icon to hide that window before recording, and then hit enter to start recording. But I think it's also very reasonable to automatically hide that window when recording starts.

**Comment by skllcrn** [comment] 2017-05-16 07:38
Duplicate of #3

**Closed** 2017-05-16 07:39 UTC
