### ISSUE TITLE
Kap control window visible when recording.

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#132] opened 2017-01-17 16:55 UTC
**Platform:**
Darwin Steves-iMac.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**Kap Version:**
1.0.0 (1.0.0.134)

### Steps to reproduce
Launch Kap.
Begin a recording on an area of the screen where Kap's 'area' marquee is *underneath* the Kap control-panel-window that drops down from the menubar.

### Current behaviour
The Kap window is visible for the first few seconds of recordings.

### Expected behaviour
It's not likely to be a user-requirement to record the Kap window.  Can this be explicitly 'ignored' from any recordings?

### Workaround
If I need to record full-screen or in an area of the screen occupied by the Kap control window, there isn't really a workaround.   Alternatively, just record on some other part of the screen.

**Comment by skllcrn** [comment] 2017-01-20 11:47
This is a duplicate of #3, I'll close this one. Let us know if you encounter any other issues!

**Closed** 2017-01-20 11:47 UTC
Labels: Is Duplicate
