### ISSUE TITLE
Add support for linux

### ISSUE THREAD

**Issue by vedantnn71** [wulkano/Kap#994] opened 2021-03-18 08:27 UTC
I want to use, contribute to this project but I am unable to run this software due to incompatibility issues, please add support for Linux also.

**Comment by sindresorhus** [comment] 2021-03-18 10:30
Duplicate of #31

**Comment by sindresorhus** [comment] 2021-03-18 10:30
Check out https://github.com/SeaDve/Kooha

**Closed by sindresorhus** 2021-03-18 10:30 UTC

**Comment by karlhorky** [comment] 2023-02-26 16:40
If you're not using Wayland (which is required for Kooha), some alternatives:

- GNOME 42+ seems to have [a built-in screen recorder](https://www.phoronix.com/news/GNOME-42-Screenshots-UI)
- [Kazam](https://github.com/henrywoo/kazam) seems to be another alternative for X11
