### ISSUE TITLE
In macOS 11.14 Mojave Beta, the "Save File"-dialog is broken

### ISSUE THREAD

**Issue by oliveratgithub** [wulkano/kap#484] opened 2018-06-27 11:33 UTC
The "Save File"-dialog in Kap, appearing when clicking on "Export" a recording, is broken under macOS 10.14 Mojave (Beta 2 release). It also doesn't support the Mojave Dark Mode.

I cannot access a screenshot of the problem at the moment, but will add this later to the issue here.

Would be interesting to know, if this is an implementation issue with that feature in Kap - or coming from the OS? However, so far all other apps "Save File"-dialogues in Mojave have not shown this broken behaviour…

**macOS Version:** macOS 10.14 Beta 2 (18A314h) Mojave
**Kap Version:** Version 2.2.0 (2.2.0.880)

**Comment by dodekeract** [comment] 2018-06-28 18:06
Can reproduce/confirm. Let me know if you need more information.

**Comment by oliveratgithub** [comment] 2018-06-28 23:10
I have to add: it's still possible to save/export a recording - so no big deal. But it looks strange...

Here's a recording of the issue:
![kap export save file dialog broken - screen recording](https://user-images.githubusercontent.com/280207/42065068-2a9be3d0-7b39-11e8-9d1e-8c52611ed338.gif)

**Comment by skllcrn** [comment] 2018-07-03 18:03
Whoa, there's quite a bit going awry in that recording @oliveratgithub! Frankly, supporting 2.0 on Mojave isn't being prioritised. Instead we're optimising the next version of Kap for Mojave, and will aim to support it on macOS 10.12 or later.

**Comment by skllcrn** [comment] 2018-07-03 18:04
#223 #450

**Comment by skllcrn** [comment] 2018-09-17 09:49
Could you test to see if you're able to recreate this using [`master`](https://kap-artifacts.now.sh/master) on the latest macOS Mojave @oliveratgithub and @dodekeract?

**Comment by skllcrn** [comment] 2018-09-21 12:06
Related issue #368, this is also likely upstream.

**Comment by sindresorhus** [comment] 2018-10-04 06:36
Duplicate of #368

**Closed by sindresorhus** 2018-10-04 06:36 UTC
Labels: Help Wanted, Is Upstream, Type: Bug

**Comment by sindresorhus** [comment] 2018-10-04 06:47
Dark mode for the save dialog will be fixed by https://github.com/wulkano/kap/pull/567.
