### ISSUE TITLE
Can't export, button not responding to clicks

### ISSUE THREAD

**Issue by luxplanjay** [wulkano/kap#840] opened 2020-04-29 09:33 UTC
**macOS version:** 10.13.6
**Kap version:** 3.2.0

#### Steps to reproduce

Install > launch > hit record > hit stop recording

#### Current behaviour

Export button does not respond and nearby options are empty

[Here's a link to screenshot of the UI](https://monosnap.com/file/GCHoq6SqmABhlrGjOj2hOuv5ejMCYG)

#### Expected behaviour

Should let me export

**Comment by karaggeorge** [comment] 2020-04-29 15:02
This is duplicate of #824 

We fixed this and we are releasing a new version of Kap with the fix really soon

**Closed by karaggeorge** 2020-04-29 15:02 UTC
