### ISSUE TITLE
A problem that I can only record at the first time after I restart my computer.

### ISSUE THREAD

**Issue by Sophia910920** [wulkano/Kap#1062] opened 2021-12-13 11:42 UTC
**macOS version:**    Big Sur (11)
**Kap version:**      3.5.1

#### Workaround

When I try to record at the second time, the error below is shown.

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)

**Comment by skllcrn** [comment] 2021-12-13 11:47
Closing as duplicate of #1059.

**Closed by skllcrn** 2021-12-13 11:47 UTC
