### ISSUE TITLE
Bug: Kap will attempt to save the original, and then the file disappears after not fully being saved.

### ISSUE THREAD

**Issue by jasikpark** [wulkano/Kap#983] opened 2021-02-26 00:15 UTC
**macOS version:**    Big Sur (11)
**Kap version:**      3.3.2

#### Steps to reproduce

Record a video, attempt to "save original" via File -> Save Original

#### Current behavior

Kap attempts to save the original, which shows up in Finder after it has saved a few apparent megabytes (though Finder might just be slow updating), and then it disappears from finder and does not complete saving, without any error or logging.

#### Expected behavior

File -> Save original saves the original video recorded successfully, for use in Handbrake or other options.

#### Workaround

Find the temporary file in /private/var/ and copy it directly, but that's not the best.

**Comment by skllcrn** [comment] 2021-03-12 17:24
I'm unable to reproduce this on Big Sur 11.2.3, are you still experiencing this @jasikpark?

**Comment by jasikpark** [comment] 2021-03-13 09:23
I have not been using Kap recently, but I can try it again - I can't remember whether this was in the context of a filled up harddrive or not? Where the recording took up the disk except a couple tens of megabytes?

**Comment by skllcrn** [comment] 2021-03-14 14:53
Thank you @jasikpark, IIRC we warn if you ran out of available space in the export destination. I'll close this issue for now, but will re-open if you are able to reproduce!

**Closed by skllcrn** 2021-03-14 14:53 UTC
Labels: Can't Reproduce

**Comment by huwan** [comment] 2021-08-25 03:12
Same issue here for Kap Version 3.3.2 (3.3.2.1718) on macOS bigsur and Mojave.

I was able to fix this by [enabling Full Disk Access in macOS Mojave (10.14) and higher](https://support.avast.com/en-us/article/Mac-full-disk-access/) for Kap. Note that Kap will not have full disk access until it it quit after enabling full disk access. So [find the original file in /private/var/](https://github.com/wulkano/Kap/issues/823#issuecomment-612488664) and copy it before quitting Kap.
