### ISSUE TITLE
Save modal crashes when expand/collapse

### ISSUE THREAD

**Issue by matsumurae** [wulkano/kap#427] opened 2018-03-13 14:38 UTC
**Platform:** Mac OS High Sierra (10.13.3)
**Kap Version:** 2.0
### Steps to reproduce
Make a capture and try to export, any type will do the same. Try opening the save as expand to view the directory location, you will get an overlay. If you close and try again, you will get the modal expanded. This works in reverse, if you close now next time you'll get closed.
Stranger things happens.

### Current behaviour
Expand/collapse doesn't opens when you click on it. You need to close and try again. This is a bit annoying and confusing.
<img width="450" alt="img" src="https://user-images.githubusercontent.com/1831932/37348147-b6f5af74-26d3-11e8-87e7-c58ef3ae111f.png">

### Expected behaviour
Same as mac has.

### Workaround
Close the modal and try again. A little annoying.

I forget to tell that I feel that the modal width isn't correct, it gets the capture width and if it's small it doesn't fit correctly. It cuts off.

**Comment by skllcrn** [comment] 2018-03-17 20:31
Thanks! Closing as it's a duplicate of #368.

**Closed by skllcrn** 2018-03-17 20:31 UTC
