### ISSUE TITLE
Feature idea: ability to select multiple output formats

### ISSUE THREAD

**Issue by rafal-olszewski** [wulkano/kap#222] opened 2017-08-30 14:21 UTC
**Platform:** Darwin Rafal-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
**Kap Version:** 1.0.1
### Current behaviour
Currently, you can only select one output format: *gif* or *webm* or *mp4*
### Expected behaviour
Use checkboxes instead of radio buttons (not sure - didn't check the source code), and add a requirement to have selected at least one checkbox for output format:
![image](https://user-images.githubusercontent.com/29777438/29877212-47527f3a-8d9f-11e7-864a-48ee624652b6.png)

### Workaround
Currently to work this around, you would have to record the same scenario 2 times. For an example, if you would like to get webm & mp4 file out of the same scenario.

**Comment by CodeTheory** [comment] 2017-08-30 14:27
Hi there @rafal-olszewski! 
Thanks for the feature request. I can happily say that this is already implemented! If you run the current version on `design/2.0`, you'll be able to record a clip and export it multiple times to multiple formats!
You can grab that version [here](kap-artifacts.now.sh/design/2.0), before release!

Although this issue is a duplicate of #163, I'm going to leave this open because we closed the other and it was hard to find.

Thanks again!

**Comment by rafal-olszewski** [comment] 2017-08-30 14:37
Awesome, that's really helpful 😄 

Is there any place I could check for already implemented features ? I have another one, to select a window while choosing a region to record - would work like `cmd + shift + ctrl + 4 --> space` on OS X, to take screenshot of window.

**Comment by CodeTheory** [comment] 2017-08-30 14:51
We try and keep all of our upcoming features in open issues though we don't have a list of features Kap currently has. I guess you could use the closed issues but it might get a bit messy.

Kap currently supports <kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>5</kbd> to open the cropper and then <kbd>Enter</kbd> to record!

**Comment by skllcrn** [comment] 2017-10-23 21:48
This will ship in the next update @rafal-olszewski

**Closed** 2017-10-31 14:11 UTC
Labels: Status: In Progress, Status: Planned, Type: Feature
