### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by ashleywang6** [wulkano/Kap#1106] opened 2022-04-03 19:50 UTC
**Sentry Issue:** [KAP-BPF](https://sentry.io/organizations/wulkano-l0/issues/2991710194/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.5.4

```
Unhandled Promise Rejection

Error: Command was killed with SIGTRAP: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:187:17)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:66)
    at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:18:129)
```

**Comment by timothyis** [comment] 2022-04-04 08:54
Duplicate of #1070

**Closed by timothyis** 2022-04-04 08:54 UTC
Labels: Sentry

**Comment by ashleywang6** [comment] 2022-04-04 22:55
Sorry how could I resolve this issue? Currently, I'm unable to use the app. 
Thanks!

**Comment by jim-alexander** [comment] 2023-07-23 01:34
Just got to say that was a really sweet bug to issue flow. Seriously impressive error handling.

Edit: I would screen record it and send it to my team as inspiration but I can't use the app :hehe:
