### ISSUE TITLE
The recording could not be paused.

### ISSUE THREAD

**Issue by Rainywink** [wulkano/Kap#1011] opened 2021-05-07 11:49 UTC
**macOS version:**    Mojave (10.14)
**Kap version:**      3.3.2

#### Steps to reproduce
After using kap for recording nearly 3 hours.
#### Current behavior
The recording could not be paused.
#### Expected behavior
Stop recording and exporting video files.
#### Workaround
Zoom and Chrome are running.

**Comment by skllcrn** [comment] 2021-05-07 22:31
Closing as duplicate of #129

**Closed by skllcrn** 2021-05-07 22:31 UTC
