### ISSUE TITLE
When a recording is open, a second recording will not show up

### ISSUE THREAD

**Issue by oliveratgithub** [wulkano/kap#480] opened 2018-06-15 10:35 UTC
When I did a recording and I have that recording open in the edit/Export player window, and then do another second, new screen recording, the second one will not open in a new edit/Export Player window - the first recording will be the only one visible.

## How to reproduce
• make a recording, finish it
• recording edit/Export window opens
• keep the window open
• Start a new screen recording
• finish the second recording

### Actual behaviour
For the second recording, after finishing it, no edit/Export player window is displayed.

### Expected behaviour
For any number of new recordings, while finishing/stopping them, each should open in a new additional edit/Export Player window.

### Affected version
* macOS High Sierra 10.13.5 (17F77)
* Kap Version 2.2.0 (2.2.0.880)

**Comment by skllcrn** [comment] 2018-06-15 10:54
Which version of Kap and macOS are you using? You shouldn't be able to start a second recording while having one open, though that functionality is in progress (#263).

**Comment by oliveratgithub** [comment] 2018-06-15 10:56
@skllcrn updated the version information in the initial issue report

**Comment by skllcrn** [comment] 2018-06-15 11:01
Very strange, running 2.2.0 I'm getting the intended behaviour and am not able to open Kap to start a new recording while having an existing one open in the Editor.

**Comment by oliveratgithub** [comment] 2018-06-27 11:20
Hi @skllcrn 
Sorry for the delay with my response. I reproduced the issue today with Kap version Version 2.2.0 (2.2.0.880)

### Pre-requisites
* In Kap's settings, enable _"Keyboard shortcut to record" (Command+Shift+5)_

### Here's how to reproduce:
* make a recording, finish it
* recording edit/Export window opens
* keep the window open
* Start a new screen recording *using the keyboard shortcut `Command`+`Shift`+`5`*
  (sometimes required to press the combination multiple times)
  * A recording scope-area with show up
  * Pressing the keyboard shortcut again, will start a new/2nd Recording

Can you reproduce it with this information?

**Comment by skllcrn** [comment] 2018-07-03 19:45
Thank you, @oliveratgithub! Can reproduce, though it doesn't actually *start* a second recording. The fix is to not allow triggering the cropper while one is being exported.

**Comment by skllcrn** [comment] 2018-09-24 16:32
Fixed in #494

**Closed by skllcrn** 2018-09-24 16:32 UTC
Labels: Good First Issue, Help Wanted, Type: Bug
