### ISSUE TITLE
Exporting to MP4 (AV1) takes a ridiculously long time

### ISSUE THREAD

**Issue by naturecodevoid** [wulkano/Kap#1000] opened 2021-03-31 17:35 UTC
**macOS version:** 10.14.6
**Kap version:** 3.3.2

#### Steps to reproduce

1. Capture a short video
2. Export at MP4 (AV1)
3. Observe

#### Current behaviour

It takes very long to export, I haven’t tested if it will ever finish as the estimated time remaining went up as I waited.

#### Expected behaviour

Similar export time to MP4 (H264)

#### Workaround

Don’t think there is one.

Notes:
- Estimated time remaining only went up
- MP4 (H264) does not experience this problem

**Comment by sindresorhus** [comment] 2021-03-31 17:55
Duplicate of #939

**Closed by sindresorhus** 2021-03-31 17:55 UTC
