### ISSUE TITLE
Recording captures Kap drop-down

### ISSUE THREAD

**Issue by johnsaddington** [wulkano/kap#118] opened 2016-12-14 20:18 UTC
Could be solved by #115 ... but, it should be fixed in isolation:

![kapture 2016-12-14 at 12 16 09](https://cloud.githubusercontent.com/assets/24398345/21199188/4996e322-c1f7-11e6-92b7-2c92e75f9564.gif)

Be great for the resulting .gif to not include the Kap dropdown in the export (as you can see above). It also captures the drop-down at the end too when you stop recording. messes up the gif.

**Comment by skllcrn** [comment] 2016-12-14 20:40
This is a tricky one. We're looking into it!

**Comment by CodeTheory** [comment] 2016-12-14 20:47
This is a duplicate of #3. But I think we may have a solution that we're working on. Thanks for the issue.

**Closed by CodeTheory** 2016-12-14 20:47 UTC
Labels: Priority: High, Status: Help Wanted, Type: Bug, Type: Performance
