### ISSUE TITLE
Unable do drag the Kap dropdown and getting an error on attempting to save

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#387] opened 2018-02-07 16:59 UTC
I mistakenly overwrote v1 of Kap when installing the release from https://getkap.co/ does anyone have a copy I can grab please?  v2 is not progress in my humble, and certainly not usable atm macOS 10.12.6

1) After installing Kap the first thing I tried to do was drag the Kap dropdown out of the way, after clicking on the Kap menu item - as I used to be able to do.  But it seems I'm now unable to un-pin it from the menu bar.  Is that expected?

2) So I battled on with the dropdown obscuring what I wanted to see underneath it, did my recording and bang - "Error In Plugin" when attempting to save a .MP4.

Steve

![columbia_county_web_ui](https://user-images.githubusercontent.com/12557929/35929713-02dd7e6a-0c28-11e8-9585-74ea317aadf0.png)

**Comment by timothyis** [comment] 2018-02-07 17:04
1. We disabled this to test whether anyone would miss it. You're part of the minority that does. We'll probably re-enable it in an upcoming release.

2. This seems like a duplicate of #377

> v2 is not progress in my humble, and certainly not usable atm macOS 10.12.6
What does this mean? 

Kap 2 has many new features while retaining simplicity, how is that not progress? 
We'd love to make progress based on your feedback.

For the time being you can download a previous release from https://github.com/wulkano/kap/releases

**Closed by timothyis** 2018-02-07 17:04 UTC

**Comment by steveharman** [comment] 2018-02-07 17:08
I'm sure the new features are great but the feature I'd most like from Kap is to be able to save the .mp4 recordings I make, which it currently doesn't seem to do for me and v1 did. That's why I didn't feel v2 was progress.

I can do screen recordings with Quicktime Player but that doesn't (afaik?) save as .mp4.

Anyway I'll revert to v1.  Thanks for the link

Steve

**Comment by skllcrn** [comment] 2018-02-07 17:32
@steveharman Have you had any Kap plugins installed at any point, in this or other versions including the Beta? What I'd try before downgrading is completely uninstalling any plugins and the app itself, and then try again on a clean install.

**Comment by steveharman** [comment] 2018-02-07 17:45
I haven't intentionally installed any pligins @skllcrn 

Didn't in fact realise there was a plugin mechanism until I saw the error about it.

**Comment by skllcrn** [comment] 2018-02-07 17:46
Okay, thanks for clarifying. Can you try again on a clean install?
