### ISSUE TITLE
Feature Request: Wait for 3 seconds before beginning

### ISSUE THREAD

**Issue by hacker-DOM** [wulkano/kap#1151] opened 2022-11-07 13:48 UTC
Loom has this option and it is very nice :-) I couldn't find this functionality in the preferences or plugins

**Comment by dinbtechit** [comment] 2022-11-10 12:47
Currently, it does take 3 secs before beginning. Maybe Kap could add customizable start times with a count down timer.

https://github.com/wulkano/Kap/issues/1144

**Comment by timothyis** [comment] 2022-11-11 09:56
Duplicate of #1144 indeed.

**Closed as completed by timothyis** 2022-11-11 09:56 UTC
Labels: Is Duplicate
