### ISSUE TITLE
Error: Could not start recording within 5 seconds

### ISSUE THREAD

**Issue by eltintero** [wulkano/Kap#854] opened 2020-05-29 22:09 UTC
I get this error every time I use KAP:
I have to restart the app to make it work.
Thanks!

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)

**macOS version:** 10.14.6
**Kap version:** 3.2.2 (3.2.2.1577)

**Comment by seanders** [comment] 2020-07-06 18:44
Seeing this same issue, just adding some data points:
**macOS version:** 10.14.6
**Kap version**: 3.2.2 (3.2.2.1577)

Fwiw, I've restarted Kap several times. The issue persists.

**Comment by TristanBrotherton** [comment] 2020-07-09 15:59
I am also seeing this issue - I have killed the application support folder, reinstalled kap. Same deal. Catalina 10.15.5

**Comment by karaggeorge** [comment] 2020-07-09 18:46
@sindresorhus I know we throw this after we make the call to aperture if it doesn't print `R` within 5 seconds. Do you know why this would happen in the Aperture code? Is there a way to send back some sort of reason as to why it didn't? Might help us debug

**Comment by sindresorhus** [comment] 2020-07-10 06:36
@karaggeorge I have no idea. It means that Aperture didn't throw any error, so why it didn't start is difficult to figure out when we cannot even reproduce the issue. Maybe the computer is just very slow. Maybe we should change the timeout to 10 seconds?

**Comment by TristanBrotherton** [comment] 2020-07-10 06:47
This was on a Mac Pro with 64gb of ram. Doubt it was execution speed.

**Comment by sindresorhus** [comment] 2020-07-10 06:51
Then my only other guess is a permission issue.

@TristanBrotherton Can you quit Kap, run this command in the Terminal, and then launch Kap again and try recording?

```
$ tccutil reset All com.wulkano.kap
```

**Comment by karaggeorge** [comment] 2020-07-10 13:23
I thought screen recording permissions were introduced in Catalina. Most of the reports I see above were on 10.14. Would it be the microphone permission?

**Comment by sindresorhus** [comment] 2020-07-10 13:46
Yeah, that was my thinking.

**Comment by karaggeorge** [comment] 2020-07-10 15:18
How about we check for mic access, and if it's not granted, we just remove the deviceId. It should have audio enabled since the cropper has logic to ask for permission, but if it somehow gets there we can at least try to prevent it?

**Comment by sindresorhus** [comment] 2020-07-12 11:30
Sure, wouldn't hurt. We should add some Sentry logging though, so we can track whether it happens to a lot of people.

**Comment by skllcrn** [comment] 2020-10-18 22:06
Closing in favour of #921. Please make sure you are running the [latest release](https://getkap.co/download), and leave any additional information on the new issue if you continue experiencing this after updating.

**Closed by skllcrn** 2020-10-18 22:06 UTC
Labels: Can't Reproduce, Help Wanted, Type: Bug
