### ISSUE TITLE
[ BUG ] Delay before recording

### ISSUE THREAD

**Issue by ibehnam** [wulkano/Kap#1133] opened 2022-08-13 18:39 UTC
On MacBook Pro with M1 Pro chip, Kap starts recording 3-4 seconds after I press record. These plugins are enabled:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/58621210/184506666-0425582f-65e4-4f84-9efd-d3bfeb9ada3b.png">

**Comment by Kooshaba** [comment] 2022-08-28 14:13
I also see this on M1 Pro.

**Comment by ibehnam** [comment] 2022-09-12 22:34
Is there any news on this? I can still see it in the latest version.

**Comment by cipri-tom** [comment] 2022-09-27 15:11
It also happens on the Intel macbook

**Comment by chrissnyder2337** [comment] 2022-10-18 20:28
Is issue #1125 related?

**Comment by timothyis** [comment] 2022-11-11 09:46
I think this is a duplicate of #1125 indeed. Closing in favour of that issue.

**Closed by timothyis** 2022-11-11 09:46 UTC

**Comment by ibehnam** [comment] 2022-11-23 05:38
But this is different than #1125 (which is about delay in selection not recording).
