### ISSUE TITLE
Remove kap screen before recording starts

### ISSUE THREAD

**Issue by freelancesam** [wulkano/kap#151] opened 2017-02-24 14:27 UTC
**Platform:**
OSX

**Kap Version:**
1

### Steps to reproduce
Start recording with focussed area under kap screen

### Current behaviour

Kap screen takes too long to close and ends up being in the recording.

### Expected behaviour

UI should close before recording begins

**Comment by CodeTheory** [comment] 2017-02-24 14:28
Duplicate of #3

**Closed by CodeTheory** 2017-02-24 14:28 UTC
