### ISSUE TITLE
App completely unuseable

### ISSUE THREAD

**Issue by iamtirado** [wulkano/kap#159] opened 2017-03-23 16:57 UTC
**Platform:**
macOS Sierra 10.12.3
![image](https://cloud.githubusercontent.com/assets/13579055/24259870/8b95878c-0fc8-11e7-91eb-18cd9d2a78fc.png)

**Kap Version:**
1.0.1
### Steps to reproduce
Opening App. Nothing works. First attempted with a second display, but does not work with single display either.
### Current behaviour
It seems that no buttons are clickable. Nothing happens when I click buttons on the app. I cannot even quit the app without using the activity monitor.

![screen recording 2017-03-23 at 12 50 pm](https://cloud.githubusercontent.com/assets/13579055/24259612/c44d8530-0fc7-11e7-91a6-0b1203d69c1f.gif)
### Expected behaviour
I expect to be able to use the app.
### Workaround
 I have found no workaround. I even uninstalled the app and installed the latest update a month apart. Still have the same issue.

**Comment by andreleon** [comment] 2017-03-28 09:05
I have the exact same issue
![screen shot 2017-03-28 at 11 05 02](https://cloud.githubusercontent.com/assets/1391492/24397403/6a8a072a-13a6-11e7-99f8-bda056c89bcf.png)

**Comment by skllcrn** [comment] 2017-03-28 09:45
This is really strange. A couple of questions, are you able to drag the app off the menubar and/or access preferences? If you are able to access preferences, does it allow you to change any settings? 

Also wondering if you have or have had issues like this in other Electron apps? Anything about your system you think could be of interest?

**Comment by matheuss** [comment] 2017-03-28 09:52
Please try `Command + Option + I` – the DevTools should pop up. Then, please go to the console and take a screenshot if there's any relevant info there 👌

**Comment by iamtirado** [comment] 2017-03-28 10:44
@skllcrn I can drag it off the menu bar, but can't access preferences.

@matheuss Here's a screenshot of the console log.
![image](https://cloud.githubusercontent.com/assets/13579055/24401324/f495cb0e-1381-11e7-9265-83ca6cbc2a95.png)

**Comment by matheuss** [comment] 2017-03-28 10:49
Thank you, @iamtirado! That's very useful – we'll release a patch this weekend.

Could you also try to go to a terminal and run `cat ~/Library/Application\ Support/Kap/Settings`? If such file doesn't exist, please try `ls ~/Library/Application\ Support/Kap`

**Comment by andreleon** [comment] 2017-03-28 10:50
I get the same console.log ![screen shot 2017-03-28 at 12 50 04](https://cloud.githubusercontent.com/assets/1391492/24401534/1a2865ec-13b5-11e7-9c38-bd6f11e852d9.png)

**Comment by matheuss** [comment] 2017-03-28 10:51
Amazing, thank you too @andreleon. Definitely an easy fix and will definitely be out this weekend 🙌

**Comment by andreleon** [comment] 2017-03-28 10:51
<img width="588" alt="screen shot 2017-03-28 at 12 51 03" src="https://cloud.githubusercontent.com/assets/1391492/24401577/39d03690-13b5-11e7-85aa-c14ec0e58bdf.png">

**Comment by torkiljohnsen** [comment] 2017-05-10 20:12
How about that patch on this 
![image](https://cloud.githubusercontent.com/assets/318089/25919043/bb6c18ba-35cd-11e7-8ba3-16c158a8f728.png) issue? 😏

**Comment by CodeTheory** [comment] 2017-05-10 20:14
We haven't had a lot of time recently @torkiljohnsen. Contributions welcome 🙂

**Comment by torkiljohnsen** [comment] 2017-05-11 06:14
@CodeTheory I wouldn't know where to start 🙂  I just heard good things about Kap and wanted to try it out, but it is not working at all. The program window opens underneath the icon, but no buttons are clickable and the controls panel won't open at all.

**Comment by CodeTheory** [comment] 2017-05-11 09:51
@torkiljohnsen I'll try and find some time on the weekend to resolve this for you. ❤️

**Comment by matheuss** [comment] 2017-05-12 23:58
Just pushed a fix 🙏 Could you guys please try it? https://kap-artifacts.now.sh/master @torkiljohnsen @andreleon @iamtirado 🙌

**Comment by matheuss** [comment] 2017-05-13 00:01
Just pushed a fix 🙏 Could you guys please try it? https://kap-artifacts.now.sh/master @torkiljohnsen @andreleon @iamtirado 🙌

**Comment by iamtirado** [comment] 2017-05-13 00:47
I have no idea where it's saving the videos or gifs if it's actually saving them. And when I go to preference I have no response when clicking [Choose]

![screen recording 2017-05-12 at 08 44 pm](https://cloud.githubusercontent.com/assets/13579055/26020990/e814c2d6-3753-11e7-9be0-d3b545e2e7df.gif)

When I choose Save to WebM, it stays stuck on "Processing..."
![image](https://cloud.githubusercontent.com/assets/13579055/26020995/250b632a-3754-11e7-9887-e23a721bd21b.png)

When choosing GIF or mp4, it seems to cancel the recording when I hit stop. It doesn't notify me of any further activity.

**Comment by torkiljohnsen** [comment] 2017-05-13 12:28
Exactly the same issues as @iamtirado above. 

Console shows this:
![image](https://cloud.githubusercontent.com/assets/318089/26025380/9cb96e48-37e6-11e7-9c7e-4e44f36f7e4d.png)

Recording looks like it's working, but I have no way of setting the "Save to…" location, and I am unable to locate any new gif file on my computer after doing a 10 second test recording.

**Comment by sindresorhus** [comment] 2017-05-14 11:43
@matheuss I noticed a potential problem. You only apply the default settings if getting audio sources succeed, but if it fails, it will fail silently and not apply those. Maybe that's the cause? https://github.com/wulkano/kap/blob/8a4530b8dfe8ab6d48fe6c332ebb809c5dfd413f/app/src/common/settings-manager.js#L49-L50

**Comment by matheuss** [comment] 2017-05-14 21:38
Uhh @sindresorhus good catch 😄 
```
  // TODO: if no input device is available (could happen in an iMac, for example), we need
  // to tell the user
  // TODO: rewrite this comment (it's 4AM and i'm fucking tired)
```
@torkiljohnsen @iamtirado are you guys on an iMac? 😄

**Comment by iamtirado** [comment] 2017-05-14 21:55
Yup.  First iMac 5K

—
Eric Tirado
Brand Design | Web Development
erictirado1@gmail.com
678-577-8064

**Comment by torkiljohnsen** [comment] 2017-05-14 22:22
No. Mid 2014 MacBook Pro, 15-inch, retina
macOS Sierra 10.12.3

**Closed** 2017-05-26 15:04 UTC
Labels: Priority: OMG MAXIMUM, Status: Help Wanted, Type: Bug
