### ISSUE TITLE
Tried to start a recording after initial install and got an error

### ISSUE THREAD

**Issue by mackness** [wulkano/kap#670] opened 2019-05-07 14:37 UTC
**macOS version:**
macOS Mojave 10.14.4
**Kap version:**
Version 2.2.0 (2.2.0.880)

#### Steps to reproduce

Install Kap for the first time and start a recording.

#### Current behaviour

Error message with the output specified below.
```
Unhandled Promise Rejection
Error: Call `.startRecording()` first
    at Aperture.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:141:13)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:207:39)
    at Generator.next (<anonymous>)
    at step (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:191)
    at file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:99)
    at EventEmitter.stopRecording (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:223:20)
```
#### Expected behaviour

Be able to record without error.

#### Workaround

n/a

**Comment by skllcrn** [comment] 2019-05-07 14:46
Duplicate of #596

**Closed by skllcrn** 2019-05-07 14:46 UTC
