### ISSUE TITLE
Unable to do full screen recording

### ISSUE THREAD

**Issue by faxotherapy** [wulkano/Kap#972] opened 2021-01-12 11:22 UTC
- macOS version:        10.14.6 Mojave
- Kap version:          3.3.2
- Step to reproduce:    not easy to reproduce, it happens often, but not every time.
- Current behavior:     Error message popping out.
- Expected behavior:    I expected Kap to start full screen recording.
- Workaround:           Quit Kap, start it again. However, screen recording might still fail. Quit Kap again and start it again. Screen recording may work.

#### Steps to reproduce
In my case, full screen recording, but does not happen every time. It does happen often.

#### Current behaviour
The current behavion is to show this error message:
```
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (~/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)
```

#### Expected behaviour
I expected Kap to record my full screen.

**Comment by skllcrn** [comment] 2021-01-25 00:39
Closing as duplicate of #921. Thank you @faxotherapy.

**Closed by skllcrn** 2021-01-25 00:39 UTC
