### ISSUE TITLE
Support for only record Internal Audio

### ISSUE THREAD

**Issue by jet10000** [wulkano/Kap#980] opened 2021-02-17 02:12 UTC
QuickTime player can support record internal audio, but just support Audio Recroding, not support Screen Recroding.

**Comment by sindresorhus** [comment] 2021-02-17 08:17
Kap is a screen recorder. We don't have any plans to only record audio.

**Comment by sindresorhus** [comment] 2021-02-17 08:17
Duplicate of https://github.com/wulkano/Kap/issues/735

**Closed by sindresorhus** 2021-02-17 08:17 UTC

**Comment by jet10000** [comment] 2021-02-17 08:55
> Kap是一个屏幕录像机。我们没有计划只录制音频。

I expect to be able to record internal sounds while recording the screen, not external sounds.

**Comment by jet10000** [comment] 2021-02-17 08:55
> Duplicate of #735

I expect to be able to record internal sounds while recording the screen, not external sounds.

**Comment by skllcrn** [comment] 2021-02-17 14:19
To record system audio, you can install the Soundflower plugin for Kap via Preferences @jet10000!
