### ISSUE TITLE
Hide cursor not working on High Sierra 10.13.5

### ISSUE THREAD

**Issue by equinusocio** [wulkano/kap#477] opened 2018-06-11 15:50 UTC
**macOS Version:** 10.13.5
**Kap Version:** 2.2.0

#### Steps to reproduce
Uncheck the **show mouse cursor** toggle

#### Current behaviour
Mouse cursor is recorded

#### Expected behaviour
Mouse cursor should be hidden from records

**Comment by albinekb** [comment] 2018-06-11 15:53
Can't reproduce on `10.13.4 (17E202)`

**Comment by equinusocio** [comment] 2018-06-11 15:55
Here a gif recorded with kap
![kapture 2018-06-11 at 17 54 49](https://user-images.githubusercontent.com/10454741/41242739-a1dde7dc-6da0-11e8-9609-0adc403ef48e.gif)

**Comment by albinekb** [comment] 2018-06-11 15:57
I'm updating to 10.13.5 now and will see if I can reproduce and check what's up here 👍

**Comment by albinekb** [comment] 2018-06-11 16:00
Must be a bug with 10.13.5 then? 🤔 
https://github.com/wulkano/aperture/blob/master/swift/aperture/Recorder.swift#L34-L43
These are the lines that disables the cursor, using Apple's swift API.

**Comment by equinusocio** [comment] 2018-06-11 16:04
https://developer.apple.com/documentation/avfoundation/avcapturescreeninput/1385601-capturescursor

Maybe this link will help you. I don't know if they changed something
https://developer.apple.com/documentation/avfoundation/avcapturescreeninput/1385601-capturescursor

**Comment by albinekb** [comment] 2018-06-11 16:06
![image](https://user-images.githubusercontent.com/5027156/41243291-08b6cf40-6da2-11e8-97a8-1a5dff03b498.png)
Yeah, we're sending false to it, so maybe a bug that got introduced as part of Mojave screen capture built in? 🤔 Don't know. Need to dig deeper.

**Comment by equinusocio** [comment] 2018-06-11 16:07
Damn. So i need to wait Apple to fix this (even if they will know about it :D)

**Comment by albinekb** [comment] 2018-06-11 16:13
I've filed a bug report with apple... Don't think there's anymore we could do here :/

**Comment by equinusocio** [comment] 2018-06-11 16:17
@albinekb There is a public link?

**Comment by sindresorhus** [comment] 2018-06-11 16:24
@albinekb Make sure you mirror it on https://openradar.appspot.com and paste a link here ;)

**Comment by albinekb** [comment] 2018-06-11 16:31
https://openradar.appspot.com/radar?id=4935854782939136

**Comment by equinusocio** [comment] 2018-06-11 16:41
Thank you guys
-- 
Mattia Astorino

Il giorno 11 giugno 2018 @ 18:31:12, Albin Ekblom (notifications@github.com)
ha scritto:

**Comment by equinusocio** [comment] 2018-06-12 14:06
@albinekb I have a bad news. With another (older) Mac with same OS version i don't have this issue (with any of the mentioned software)

<img width="698" alt="screen shot 2018-06-12 at 16 06 28" src="https://user-images.githubusercontent.com/10454741/41295318-93dfa19c-6e5a-11e8-88b1-83b334ed0952.png">

**Comment by albinekb** [comment] 2018-06-12 14:16
Can you check if it's the same build of 10.13.5? if you click the version number it should have the build ID there (in that window) @equinusocio

**Comment by equinusocio** [comment] 2018-06-13 07:16
@albinekb Same build (17F77) on my — not wirking — mac.

**Comment by albinekb** [comment] 2018-06-18 12:45
Update from apple. Sounds like it's a known bug, and it won't be fixed in 10.13.x. Let's hope Mojave is working like it should?
![image](https://user-images.githubusercontent.com/5027156/41536548-3414fb58-7306-11e8-9484-204b49b0b6ce.png)

**Comment by oliveratgithub** [comment] 2018-06-27 11:35
I can test this with the recent macOS Mojave Beta release. Will post here when I did so.

**Comment by skllcrn** [comment] 2018-06-27 11:50
Thank you @oliveratgithub!

**Comment by lacostenycoder** [comment] 2018-09-11 21:29
Would it kill you to support older Mac OS versions? i.e. I'm Never Getting High Sierra aka 10.11.16 aka El Capitan Who Doesn't Get High lol.

**Comment by albinekb** [comment] 2018-09-11 21:34
No, we don't have the time to test and develop for older OS, as you mentioned you can continue to use 1.0 forever. Update to take advantage of the updates.

**Comment by equinusocio** [comment] 2018-09-12 12:54
I can confirm. Fixed in Mojave

**Comment by sindresorhus** [comment] 2018-09-27 14:44
Since this is fixed on Mojave and there's nothing we can do about High Sierra and I doubt Apple will fix it there, we should just disable the input on High Sierra and add a small note telling the user about the macOS bug.

**Closed** 2018-12-27 12:12 UTC
Labels: Is Upstream, Priority: Low, Type: Bug

**Comment by GamaTellez** [comment] 2022-09-08 01:15
I’m having a similar issue with AVCaptureScreenInput and capturesCursor set to false. It works as expected if pointer size is set to normal but If i change it to anything else in Accessibility > Display > Pointer size) then the cursor shows in my screen captured even with capturesCursor still set to false. Anybody seen anything similar?
