### ISSUE TITLE
Auto-added frame/border

### ISSUE THREAD

**Issue by felixdorner** [wulkano/kap#139] opened 2017-02-03 15:18 UTC
Kap is automatically adding a subtle lightgray border/frame to my captures. Is it possible to disable this behaviour?

**Comment by skllcrn** [comment] 2017-02-04 00:50
I've noticed this under certain circumstances. I believe it's related to the method we're currently using for selecting the area to record, @sindresorhus has been researching an alternate solution that should solve this.

**Comment by skllcrn** [comment] 2017-11-01 15:45
I can't reproduce this on `[master](https://kap-artifacts.now.sh/master)`, can you confirm @felixdorner?

**Comment by sindresorhus** [comment] 2018-01-19 18:32
Closing as it can no longer be reproduced in the latest beta.

**Closed by sindresorhus** 2018-01-19 18:32 UTC
Labels: Priority: High, Type: Bug
