### ISSUE TITLE
Recording disappears once stopped

### ISSUE THREAD

**Issue by aalokt89** [wulkano/kap#676] opened 2019-05-24 18:59 UTC
**macOS version:** 10.14.3
**Kap version:** 3.0.0-beta 5

#### Steps to reproduce
1. click Kap icon
2. drag mouse to set recording frame
3. press record and press 'stop' icon when done recording

#### Current behaviour
Kap UI disappears but nothing else happens. No notification of completed capture. When I check the output folder, no file has been exported.

#### Expected behaviour
I should get a notification that my recording is complete and has been exported to the destination folder

**Comment by skllcrn** [comment] 2019-05-24 20:29
Once you stop you recording, does a preview of it open? If so, could you send a screenshot of that window @aalokt89?

**Comment by aalokt89** [comment] 2019-05-24 20:47
So now keep getting an Error alert saying it could not run within 5 seconds. And then it freezes and I have to force quit through the Activity Monitor.
https://www.dropbox.com/s/1n22v6r7unrjbr4/KapBug.mov?dl=0

**Comment by skllcrn** [comment] 2019-05-24 20:55
That's not the behaviour you were seeing earlier, right? If so, could you open a separate issue for that @aalokt89?

**Comment by aalokt89** [comment] 2019-05-24 21:16
Update: So the recording experience is very confusing. There seems to be a holding stage before it actually starts recording? 

STR:
1. click on Kap icon. Create capture window. Hit record
2. The elements outside of the window remain dark. The Kap icon does not have a stop icon.
3. ~5 seconds later the Kap icon has a stop icon and the screen lightens up
4. If I start moving around BEFORE the stop icon appears and then hit the stop icon, nothing happens. https://cl.ly/521c55c638ac 
5. if I wait and don't not move anything until AFTER the stop icon appears, the preview window pops up. https://cl.ly/927f766bf2a8

If that is indeed supposed to be a holding pattern until the stop icon shows up, there needs to be a much clearer UI element that lets me know this. Maybe a countdown until It's ready to record.

I also think it should stay dark outside the capture window. The lightening of the window was very unexpected and made me think it was done recording. It was also very hard to see the actual capture window

**Comment by skllcrn** [comment] 2019-05-24 21:54
Depending on your environment the recording can start almost immediately or seconds after you hit the record button. The icon should animate in the menubar while the recording is getting started, but I noticed that is missing on your setup @aalokt89:

![Kapture 2019-05-24 at 23 54 26](https://user-images.githubusercontent.com/8440026/58358465-4bd97680-7e7f-11e9-935b-13f82c71a988.gif)

**Comment by aalokt89** [comment] 2019-05-25 00:59
Here are better quality screencast of the bug. But now it's not working even if I wait until the stop icon appears...

Before stop icon: https://cl.ly/a7b6fd0f1750
After stop icon: https://cl.ly/ea38d6728517

In either case, The appearance of the stop icon is barely noticeable. User's are not naturally looking in that area when they need to focus on what they are planning to record. I assume that once I click on the record button, I can start recording. I still think there needs to be some sort of directional UI that says "wait/start' when it's not ready and a ready to record.

**Comment by sindresorhus** [comment] 2019-05-25 05:29
> I still think there needs to be some sort of directional UI that says "wait/start' when it's not ready and a ready to record.

I agree, it's not clear enough.

For example, Capto.app has this in the center of the screen when preparing to record:

<img width="380" alt="Screen Shot 2019-05-25 at 12 28 36" src="https://user-images.githubusercontent.com/170270/58365043-ae1a9180-7ee8-11e9-9323-880f40e4b173.png">

**Comment by karaggeorge** [comment] 2019-09-03 21:37
The problem is that we don't exactly know when to show the tray animation or a 3..2..1 countdown, since aperture takes a few seconds to start recording but it's not always the same. We could show the 3..2..1 after aperture starts recording (currently that's what we do for the tray icon) and then trim the first 3 seconds of the video? Otherwise we mind end up with part of that display in the resulting recording

**Comment by skllcrn** [comment] 2019-09-03 21:59
That's what we've been struggling with for a while @karaggeorge. We could continue showing the overlay and UI in a disabled state with an indeterminate progress indicator until Aperture is ready? That way the UI fading out becomes a much clearer visual queue that the recording is starting alongside the animated menubar icon.

**Comment by sindresorhus** [comment] 2019-09-04 05:29
> We could show the 3..2..1 after aperture starts recording (currently that's what we do for the tray icon) and then trim the first 3 seconds of the video? Otherwise we mind end up with part of that display in the resulting recording

That's what we considered previously. Some early work you might find useful here: https://github.com/wulkano/kap/pull/283

**Comment by armanozak** [comment] 2019-09-19 09:15
I have the same problem. I am a Kap 2 user and Kap 3 Beta is not so far from what I'm already used to, so the tiny stop button is not what I find problematic. The real problem is that there is no recording. I'm pretty sure it doesn't even try to save anything, because I would have notice a peak in CPU usage at my terminal.

**What I tried so far:**
- I have tried "waiting for stop icon to appear before moving the mouse" as described above, but it didn't help. 
- I have changed the movie output directory, but that didn't help either.

**Comment by skllcrn** [comment] 2019-09-23 11:42
Could you go to About Kap in the app and check if you are on the [latest beta version](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.6) @armanozak? You can get to it by right clicking on the menubar icon and selecting it in the menu that appears.

**Comment by armanozak** [comment] 2019-09-23 12:23
I was on beta-6, but have deleted the beta now.

**Comment by skllcrn** [comment] 2019-09-23 14:01
Thank you for the report @armanozak, we're working on identifying the root cause of this. From what I understand, once you complete the recording, you are not prompted with the editor and a previewing of your recording. To me that that suggests that we weren't able to write a file at all, so there is no source file present and Kap based on these reports the app fails silently. Are you still able to reproduce @aalokt89?

**Comment by skllcrn** [comment] 2019-12-11 21:55
I'm attributing this issue to an error starting the recording, which has been fixed in versions 3.0 and newer. Thank you for you help!

**Closed by skllcrn** 2019-12-11 21:55 UTC
Labels: Help Wanted, Priority: High, Status: Community Feedback Wanted, Status: Planned
