### ISSUE TITLE
App window shows for a short period of time when starting a record

### ISSUE THREAD

**Issue by CodeTheory** [wulkano/kap#3] opened 2016-10-04 12:39 UTC

**Comment by matheuss** [comment] 2016-10-13 20:25
I just looked into this and here's what I concluded:

I put `console.log(Date.now())`s in the following locations:

https://github.com/wulkano/aperture.js/blob/99110e848368af117ee573ffe693433d0eff7ec4/index.js#L55

https://github.com/wulkano/kap/blob/fb1e5b058277bb55f6c156d1a679150ea8b5a878/app/src/renderer/js/index.js#L120

https://github.com/wulkano/kap/blob/fb1e5b058277bb55f6c156d1a679150ea8b5a878/app/src/main/index.js#L281

Result:

<img width="686" alt="screen shot 2016-10-13 at 5 05 00 pm" src="https://cloud.githubusercontent.com/assets/4721750/19365247/405e95ee-9168-11e6-9474-32c7a7d89b0c.png">

![kapture 2016-10-13 at 16 58 15](https://cloud.githubusercontent.com/assets/4721750/19365250/442daac0-9168-11e6-9757-61375f6c6b0f.gif)

Kap receives the `recording started` signal from `aperture` 7 ms after it starts and then the `mainWindow.hidden()` is called 1 ms later.

So: it's probably something on the `aperture` or Swift side and it's going to need some time to debug. Any help is more than welcome 😄

**Comment by Khaledgarbaya** [comment] 2017-01-25 13:23
is the waiting for recording started really needed? the window could be hidden and still wait for the signal. I might take a look into this tonight

**Comment by sindresorhus** [comment] 2017-01-31 07:31
@matheuss I'm not surprised. The API is async, so it's not going to resolve the promise instantly. The native API reports exactly when the screen recording starts, so there's going to be some lag.

**Comment by sindresorhus** [comment] 2017-01-31 09:20
@Khaledgarbaya It usually takes 1-2 seconds for the screen recording to start (Not us, but the system), so it's an indicator you're not being recorded yet. I can't really think of a better solution right now, so I guess we can at least do what you suggest for now.

**Comment by matheuss** [comment] 2017-01-31 10:43
@Khaledgarbaya I'm not sure if I like your idea 😕 If you want the window to be hidden, you can just leave it docked to the menubar. 

I will try and hack something during [2.0.0](https://github.com/wulkano/kap/milestone/3) 🕵️

**Comment by matheuss** [comment] 2017-01-31 10:55
Ok, just discussed with @skllcrn and we have an idea: we'll just hide the window when you click to record, and then the menubar icon will be more useful: we can show the time, a pause button etc. Something like CloudApp:

<img width="190" alt="screen shot 2017-01-31 at 8 54 39 am" src="https://cloud.githubusercontent.com/assets/4721750/22462070/edeea3ea-e792-11e6-822e-2d14f05fa7f9.png">
(Obviously with a better UI/UX, since we got @skllcrn 😎)

**Comment by skllcrn** [comment] 2017-01-31 11:04
The solution to this is another problem. As @sindresorhus and @matheuss have explained, we're limited by the API here. You want to know that Kap is "Getting ready..." and that your recording hasn't started yet, but of course you don't want the window showing in the actual recording. If we hide the window immediately, we still need to communicate that the app is working and give a clear hint as soon as we know the recording has started (which isn't accurate). 

My worry is that people will think the recording has started as soon as the app window is hidden. I'll see what I can do. I have really mixed feelings about breaking out of the established pattern of how apps are displayed and act in the menubar, the solution should feel at home in that environment.

**Comment by sindresorhus** [comment] 2017-02-01 02:50
I looked into this yesterday and we have two options:

1. In the Swift code in Aperture, handle writing the movie file ourselves. This would let us drop the frames until Kap signals it's ready and Kap would be able to record exactly when it wanted to. The problem is that it's both difficult and verbose to do anything manual with AVFoundation and we would not be able to use the simple method we're currently using. We would also need a different solution for Linux when we add support for that.

2. Save the time when `.startRecording()` is called. Have Aperture send the time back in the resolved promise when the recording actually started. Use `ffmpeg` to losslessly trim that time away from the start of the movie. This process is super fast (like you would have done it in QuickTime Player). This would also work for the Linux version without any extra code. This way we could actually have a nice countdown too as we would be fully in control of when the actual recording started.

I think `2` would be the best solution.

**Comment by SamVerschueren** [comment] 2017-06-15 05:51
I came across this bug as well. Before I started using kap, I always used LiceCap. I like how they do it. To illustrate this, I made a capture of a LiceCap capture :p.

![licecap](https://user-images.githubusercontent.com/1913805/27167085-3a6219ac-519f-11e7-8bd5-83feea3782eb.gif)

As you can see, LiceCap always uses a preroll of 3 seconds. Don't think it's configurable, but might be a nice feature. That timer could then be shown in the menubar on top. Currently, it's hard to tell how much time you have before the capture actually starts.

**Comment by sonaye** [comment] 2017-09-02 15:25
How about when we click the red record button, the window is hidden immediately then a three-to-1 counter would replace the tray icon (3 new tray icons, five in total). I noticed that the recording starts the second the tray icon becomes stop instead of recored, so it should work. Is this feasible?

**Comment by skllcrn** [comment] 2017-11-01 16:07
Fixed on [`master`](https://kap-artifacts.now.sh/master), thank you @vadimdemedes! Feel free to close this issue when you're ready.

**Comment by sindresorhus** [comment] 2018-01-19 18:32
This should no longer be a problem in the latest beta as we hide the window right away and then bounce the menubar icon while it prepares.

**Closed by sindresorhus** 2018-01-19 18:32 UTC
Labels: Status: In Progress, Type: Bug
