### ISSUE TITLE
Add option to enable lossy compression for gifs with gifsicle

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#468] opened 2018-05-21 18:09 UTC
Add an option to use https://github.com/imagemin/imagemin-gifsicle for lossless compression for GIFs, toggle in preferences: 

**Enable GIF compression**
Lossless :radio_button:
Lossy :radio_button:

Defaults to lossless.

**Comment by skllcrn** [comment] 2018-05-21 18:28
Updated the original issue description to specify the lossless option.

**Comment by skllcrn** [comment] 2018-05-25 20:43
Just realised this is a duplicate of #117

**Closed by skllcrn** 2018-05-25 20:43 UTC
Labels: Help Wanted, Status: Planned
