### ISSUE TITLE
试用感受

### ISSUE THREAD

**Issue by zkshell** [wulkano/kap#761] opened 2019-11-23 12:24 UTC
**macOS version:*10.12.6*
**Kap version:*kap3.0*

**Comment by zkshell** [comment] 2019-11-23 12:25
在视频录制时发现 音频不能内录 录制之后 导出视频 电脑风扇转速加快 导出视频时间比录制时间长 会不会在导出视频时 因死机而使录像丢失 功亏一篑。

**Comment by sindresorhus** [comment] 2019-11-23 13:51
Please write in English.

**Comment by hyahm** [comment] 2019-11-24 02:30
can not Record Sound， when open Audio recording option  the soft closing too

**Comment by oudajosefu** [comment] 2019-11-24 09:34
@sindresorhus "When recording video, it is found that the audio cannot be recorded. After recording, the video is exported. The speed of the computer fan is faster. The time for exporting the video is longer than the recording time. If the video is lost when the video is exported, the video will be lost."

**Comment by skllcrn** [comment] 2019-11-25 00:19
Closing as duplicate of #760

**Closed by skllcrn** 2019-11-25 00:19 UTC
