### ISSUE TITLE
Bottom bar appears in all recording

### ISSUE THREAD

**Issue by hanxue** [wulkano/kap#253] opened 2017-10-29 07:52 UTC
Platform: MacOS 10.10.5
Kap: 1.0.1

# Step to reproduce : 

1. Make any video recording. Does not matter what option is turned on/off

# Current behaviour:

1. There is an additional bottom bar at the bottom

See video 

https://webmshare.com/play/qNW8q

GIF version
![vscode_cannot_stop_git_command](https://user-images.githubusercontent.com/760008/32141679-032935fa-bcc1-11e7-9d88-43af03b5ba67.gif)

# Expected behaviour : 

Kap will only capture the cropped area without adding anything.

**Comment by skllcrn** [comment] 2017-10-31 10:34
Duplicate of #67

**Closed by skllcrn** 2017-10-31 10:34 UTC
