### ISSUE TITLE
Record pressed keys during recording

### ISSUE THREAD

**Issue by deadcoder0904** [wulkano/Kap#419] opened 2018-03-09 06:33 UTC
I know it can be done in [Mac OS Sierra](https://superuser.com/a/1239253) but it has some limitations like it does not show Alphabet keys + Tab & many more. 

I don't know if its in the scope of this project but it would be a great addition. 

My use case was for issues like [this](https://github.com/Microsoft/vscode/issues/45381).

Checkout the GIF in the above mentioned issue that the keystrokes that are recorded are not proper which are from Mac OS Keyboard as mentioned in the above [SuperUser answer](https://superuser.com/a/1239253)

**Comment by albinekb** [comment] 2018-03-09 13:49
I think this is a duplicate of: https://github.com/wulkano/kap/issues/158

**Comment by deadcoder0904** [comment] 2018-03-09 14:25
Yes it is good in combination. 

I think it would be great if its built-in in Kap as it is well-maintained & `keycastr` has halted development even though its one & done software.

The main reason might be all in one software for ScreenCasting. If its out of scope of this project, feel free to close this issue.

**Comment by karaggeorge** [comment] 2020-06-26 16:41
Closing this as this is now possible with https://github.com/karaggeorge/kap-key-cast

**Closed by karaggeorge** 2020-06-26 16:41 UTC
Labels: Type: Plugin Request
