### ISSUE TITLE
No audio recorded on videos

### ISSUE THREAD

**Issue by davidjb** [wulkano/Kap#489] opened 2018-07-18 12:20 UTC
**macOS Version:**
ProductName:    Mac OS X
ProductVersion: 10.14
BuildVersion:   18A391
**Kap Version:** Version 2.2.0 (2.2.0.880), but tested on Version 3.0.0-beta.1 (3.0.0-beta.1.1006) too

#### Steps to reproduce
1. Open Kap
1. Click microphone icon so audio is toggled on:
![image](https://user-images.githubusercontent.com/1002811/42880520-1f5f6d98-8a84-11e8-9521-96ae1ed80e28.png)
1. Open Preferences and confirm that 'Record audio' set to the correct device (in my case, just the standard Built-in Microphone):
![image](https://user-images.githubusercontent.com/1002811/42880581-50fafe8a-8a84-11e8-8bf8-021797905f18.png)
1. Open Sound system preferences window and confirm device is selected and levels are visible on Input tab:
![image](https://user-images.githubusercontent.com/1002811/42880645-7eb82c30-8a84-11e8-951e-8674fa566a90.png)
1. Perform a recording in Kap, keeping the Sound system preference panel open to observe levels
1. Try and play back resulting recording.  Not there is no audio in the Editor or when saving the file as an MP4.

#### Current behaviour
No audio recorded with Kap videos.  Settings all appear to be correct -- audio toggled on in Kap, device set correctly, levels are clearly visible in the Sound preference panel, but still no audio.
#### Expected behaviour
Audio should be recorded with a video.
#### Workaround
Use Quicktime Player with equivalent settings; recording works with sound; I tested this immediately after trying and failing with Kap.

**Comment by skllcrn** [comment] 2018-07-18 13:33
Thanks for the detailed issue @davidjb. Based on what you mentioned in the other issue you posted recently, it sounds like there's something not quite right with your installation of Kap. I'd like to know how you installed/updated Kap and if you had one or more instances of the app on your system from before, in addition to any others details you think might be useful.

**Comment by davidjb** [comment] 2018-07-18 13:47
As per #488, I just installed Kap for the very first time on this machine today. Fresh new install from brew cask which comes from the 2.2.0 dmg here on GH. I've uninstalled and rm -rf'd the application support directory, and reinstalled and same experience.

Never had two versions; this is the very first time I've used this on this computer.  Everything else works mind you -- video recording and saving is flawless, but audio doesn't work + the analytics-not-saving issue in #488.

**Comment by skllcrn** [comment] 2018-07-18 14:03
Thanks for the quick reply @davidjb! Really is strange, maybe there's something up with the permissions. Could you remove it again and try this build https://kap-artifacts.now.sh/next

**Comment by davidjb** [comment] 2018-07-18 15:12
Tested the new version and same issue persisting.  I saw the new / moved `Audio recording` setting and enabled that:
![image](https://user-images.githubusercontent.com/1002811/42890508-8d61fd98-8a9c-11e8-87c4-7a82e3b83586.png)

but the result is still a video that appears in the Editor window with no sound; the speaker icon is crossed out like so, which seems to indicate no audio track:

![image](https://user-images.githubusercontent.com/1002811/42890617-d0b38d78-8a9c-11e8-80da-2600cd476217.png)

UI on the new version is much more user friendly otherwise btw!

**Comment by skllcrn** [comment] 2018-09-26 20:12
We haven't had other reports of this issue @davidjb, thinking it might be due to something unique in your setup. 

Any chance you could [download the Kap Beta](https://github.com/wulkano/kap/releases/download/v3.0.0-beta.1/kap-beta-3.0.0-beta.1-mac.zip) and test if the issue is still persisting? If that doesn't work and we're no able to reproduce it I'll have to close this issue for now.

**Comment by skllcrn** [comment] 2018-10-02 12:50
Sentry issue: [KAP-3CH](https://sentry.io/wulkano-l0/kap/issues/699214572/)

**Comment by Martin-Pitt** [comment] 2018-10-19 09:56
Also having same issues, both with 2.2.0 & 3.0.0-beta.3

Never got a permission request either, while all other apps did.

![image](https://user-images.githubusercontent.com/7586051/47211540-9f399280-d38d-11e8-9d5d-c669b2a9c351.png)

**Comment by Martin-Pitt** [comment] 2018-10-19 10:05
I was googling around for other similar issues in regards to Mojave, Electron and permissions and found this as the most useful comment so far: https://github.com/electron/electron/issues/14801#issuecomment-427235881

**Comment by rhwu** [comment] 2018-11-05 19:10
Saw same issue with newly upgraded macos Mojave. Slack works fine.

**Comment by rhwu** [comment] 2018-11-05 19:37
> Did you see a prompt asking for microphone access @rhwu? I any case, could you try completely uninstalling Kap and reinstall using the [latest beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.3)?

Thanks for your quick response. I did try both v3.0.0-beta.3 and v2.2.0. Neither of them gave a prompt asking for permission.

**Comment by davidjb** [comment] 2018-11-11 12:18
@fermion Export formats are chosen _after_ recording occurs, so that shouldn't have any bearing on whether audio is captured or not.  A permission prompt should be seen when the microphone is attempted to be accessed; so before/as a recording is beginning.

Fwiw, I've re-tested with 3.0.0-beta3, now on 10.14.1 and it's the same result.  Set my Preferences to capture audio and set the audio device:

![image](https://user-images.githubusercontent.com/1002811/48312704-c78e6880-e5aa-11e8-807d-89510b040394.png)

and tried to start recording.  No prompt asking for permission, no audio recorded.

**Comment by skllcrn** [comment] 2018-11-11 12:37
Can you attempt to completely uninstall Kap (including anything in `~/Library/Application Support/Kap`) and reinstall the beta @davidjb, @rhwu and @Martin-Pitt? Once you've reinstalled, make sure audio recording in enabled in preferences and also try using the default input device. Please let me know if you get the prompt to allow microphone access at any point and if there's audio when exporting either MP4 or WebM.

**Comment by fermion** [comment] 2018-11-12 01:55
@davidjb sorry, I wasn't clear here. I'm saying that I

- installed `Kap Beta.app`
- was asked for microphone permission by the app and granted it
- recorded a short product demo video
- heard no audio on the preview window

The default export format in the preview window is for a `GIF` which wouldn't have audio. Playing the video in the preview window I heard no audio from my recording and saw the same disabled volume icon that [you linked earlier](
https://github.com/wulkano/kap/issues/489#issuecomment-405966529) in this thread.

After changing the preview's format selector to `MP4` I could hear audio when playing the preview.

I have to assume that the preview doesn't play audio when `GIF` is selected because the final output won't have audio. Selecting `MP4`, I heard it.

I think that everything's 👍 on my end here so I hope that you're able to figure out things on your machine 🤞

**Comment by Martin-Pitt** [comment] 2018-11-12 09:52
@skllcrn followed the steps and had the same results as @davidjb – No microphone prompt at any point.

**Comment by harryfear** [comment] 2019-01-18 17:39
Still having the same problem here, on MacOS 10.14.1 (18B75)

**Comment by tech4eleven** [comment] 2019-01-22 16:40
I have the same issue - no audio on recordings with newly installed Kap Beta 3.0.0.-beta.3 and Mac OS 10.14.2. Audio options in Kap beta are set to use built in microphone and microphone is confirmed working in sound preferences of mac os. audio recordings worked perfectly with Kap 2.2 but Kap 2.2 wouldn't export videos for me after Mojave so i completely uninstalled it using AppCleaner and installed Kap beta.

**Comment by Carreau** [comment] 2019-04-04 18:37
I believe I have found the reason why on my setup it can sometime not work. I at least have strong correlation; which does not imply causation, but who knows. 

I do record on an **external screen**, when my **laptop lid** is closed sounds is not recorded. 
When my laptop lid is open sounds is recorded.

Maybe some people will have the cause.

**Comment by skllcrn** [comment] 2019-04-27 14:12
This issue is a bit elusive and aspects of it might be upstream. Please continue sending reports you think might help address this issue.

**Comment by davidjb** [comment] 2019-04-28 05:16
@skllcrn Upstream as in Electron?  If so, the [existing issues around AudioContext](https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue+AudioContext) all seem to have error messages so can we run Kap in a terminal / get logging out of its Electron-packaged app?  Otherwise it seems like shooting in the dark without an error message to track or report upstream.

Fwiw, trying the latest stable Kap (v2.2.0) again today on a whim actually saw a microphone prompt appear -- that's the very first time Kap's ever shown that.  However, audio still doesn't get recorded.  Trying the latest Kap beta (v3.0.0-beta.5) shows no microphone prompt for its app and the UI in Kap is  interesting:

![image](https://user-images.githubusercontent.com/1002811/56859027-52ee9100-6974-11e9-95bc-c0ccc2af7bc3.png)

What appears to be a toggle for audio recording is empty/missing and does nothing when clicked.  The listing of audio devices is present and correct, though.

**Comment by skllcrn** [comment] 2019-04-28 23:12
That's a really good idea @davidjb, want to help? I'm struggling to wrap my head around this issue, and Chrome itself isn't exactly the best at keeping track of input and output audio. Do you think this issue could stem from somewhere in [Aperture](https://github.com/wulkano/Aperture#related) @sindresorhus? 

These are some errors I'm seeing:

>>> TypeErrorcommon:settings at null.<anonymous>
`devices.some` is not a function

>>> TypeErrornull.<anonymous>(common:settings)
`devices.some` is not a function

> Fatal error: Error raised at top level: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Built-in Microphone" `UserInfo={NSLocalizedFailureReason=This app is not authorized to use Built-in Microphone., AVErrorDeviceKey=<AVCaptureHALDevice: 0x7fa3e0d23840 [Built-in Microphone][AppleHDAEngineInput:1F,3,0,1,0:1]>, NSLocalizedDescription=Cannot use Built-in Microphone`

>>>`ErrorPromise.all.then.arr(/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js)`
Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture

**Comment by davidjb** [comment] 2019-04-29 10:58
Okay, so I just cloned/built Kap from source (commit https://github.com/wulkano/kap/commit/16729954e6056886bc79c3cdb47d2508588ba71d) and running it with `yarn start` can successfully record audio, hooray!  macOS prompts that it is a process in my terminal asking for microphone permission and upon accepting, the mic is accessed and recordings in MP4 format have audio.  No errors logged in the Developer Console, just warnings about unrelated resources being loaded over HTTP (presumably since it's a debug build).

Now, here's where things get interesting.  Running `yarn run pack` is able to successfully build the .app file but when I run it, it looks as though it's all fine (prompted for permissions, then MicroSnitch reports the mic is in use), but upon trying to start a recording it doesn't start, eventually erroring `Could not start recording within 5 seconds`, and leaving Kap in a broken state (eg black overlay still present), requiring a force quit.  The only errors in `Console.app` are:

```
# About 50 of these errors
error	20:42:43.858741 +1000	Kap	nw_path_close_fd Failed to close guarded necp fd 49 [9: Bad file descriptor]
```

```
error	20:42:11.746512 +1000	Kap Helper	CMIOHardware.cpp:339:CMIOObjectGetPropertyData the System is exiting
error	20:42:11.746607 +1000	Kap Helper	CMIO_DALA_System.cpp:264:GetPropertyData error 1970171760 (<private>) getting property selector (<private>) scope (<private>) element 0
```

```
error	20:42:50.363728 +1000	aperture	CMIOUnitFigBaseObjectImpl.c:246:CMIOUnitCreateFromDescription Invalid paramater
error	20:42:50.408021 +1000	aperture	CMIO_Unit_Input_HAL.cpp:985:GetPropertyInfo CMIOUInputBase::GetPropertyInfo failed for ID 102, Error: -67456
error	20:42:56.689724 +1000	aperture	CMIOHardware.cpp:339:CMIOObjectGetPropertyData the System is exiting
error	20:42:56.689774 +1000	aperture	CMIO_DALA_System.cpp:264:GetPropertyData error 1970171760 (<private>) getting property selector (<private>) scope (<private>) element 0
error	20:42:56.689876 +1000	aperture	CMIOHardware.cpp:339:CMIOObjectGetPropertyData the System is exiting
error	20:42:56.689926 +1000	aperture	CMIO_DALA_System.cpp:264:GetPropertyData error 1970171760 (<private>) getting property selector (<private>) scope (<private>) element 0
```
`/Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture` is the `aperture` referenced above.

So, perhaps there's something different between running as `yarn start` and `yarn run pack` leading to these differences in behaviour.  At very least, I now have a workaround for being able to use Kap 👍 

Out of interest, I also took a look at what happens when my build of Kap.app is denied microphone access (or has it turned off later), the resultant error causes Kap to crash (eg Apple's error reporter loads, which is different to the 5-second timeout above):

```
Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture {"destination":"file:///private/var/folders/1j/cstfyltx4sjcydsy9zs07ckr0000gr/T/662e83c5ee23f95a5e0dd51675334a06.mp4","framesPerSecond":30,"showCursor":true,"highlightClicks":false,"screenId":69731584,"audioDeviceId":"AppleHDAEngineInput:1B,0,1,0:1","cropRect":[[1233,537],[262,182]]}
Fatal error: Error raised at top level: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Built-in Microphone" UserInfo={NSLocalizedFailureReason=This app is not authorized to use Built-in Microphone., AVErrorDeviceKey=<AVCaptureHALDevice: 0x7fcaef4268b0 [Built-in Microphone][AppleHDAEngineInput:1B,0,1,0:1]>, NSLocalizedDescription=Cannot use Built-in Microphone}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.42/src/swift/stdlib/public/core/ErrorType.swift, line 191
```

So some graceful error handling there would be good to avoid a hard crash in the case of the user not authorising the microphone.

**Comment by harryfear** [comment] 2019-05-06 12:40
I was wondering if the Loom app and Kap app are based on the same Electron foundation? If so, it might help to understand why this issue arrises in Kap but not in Loom? I'm no a MacOS developer but it looks like they both run on Electron?
![Screenshot 2019-05-06 at 13 40 21](https://user-images.githubusercontent.com/907604/57225533-9005f380-7004-11e9-968f-2fb041c3e2a8.png)
![Screenshot 2019-05-06 at 13 39 58](https://user-images.githubusercontent.com/907604/57225535-909e8a00-7004-11e9-99d5-21c137c01828.png)

**Comment by skllcrn** [comment] 2021-01-13 03:20
There seems to be no reports of this happening on recent releases, so I'll be closing this issue now. Thanks to everyone who participated!

**Closed by skllcrn** 2021-01-13 03:20 UTC
Labels: Can't Reproduce, Help Wanted, Is Upstream, Priority: High

**Comment by rsprado** [comment] 2021-06-08 19:42
I'm having a different issue, my microphone is recorded perfectly but the MAC OS (Big Sur) sounds like a video playing, an audio, etc aren't recorded.

**Comment by ericeracy** [comment] 2021-06-26 21:36
I met with the same issue. @Carreau 's approach works for me when I am using mac microphone as sound output. But when I plug my earphone in, the audio is not recorded. (M1 Big Sur 11.14 and Kap 3.3.2)

**Comment by CamiloGarciaLaRotta** [comment] 2022-11-04 12:21
If anyone hits this issue you may just need to scroll 😮‍💨 I didn't realize the preference popup was a scrollable one and the audio settings are below the first options

**Comment by barseghyanartur** [comment] 2025-02-10 11:08
Is there a way I could capture the system output in the recorded video? Say, I want to demo a new text-to-speech feature which plays nicely through my speakers, but doesn't appear in the recording.
