### ISSUE TITLE
Gif support 

### ISSUE THREAD

**Issue by sirgalleto** [wulkano/kap#24] opened 2016-10-06 15:08 UTC
Can you export gif like recordit app?

**Comment by doot0** [comment] 2016-10-06 15:09
Hey, closing this as it's a dupe of https://github.com/wulkano/kap/issues/14.

It's in the works and should be landing soon! Thanks for your patience. 👌

**Comment by sirgalleto** [comment] 2016-10-06 15:12
@doot0 thanks and congrats, this app looks very nice

**Comment by doot0** [comment] 2016-10-06 15:14
@sirgalleto Thanks boss! 🖖

**Comment by matheuss** [comment] 2016-10-07 20:52
Ops, closed by accident 😩

**Closed** 2016-10-07 21:05 UTC
