### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by newforms** [wulkano/Kap#1142] opened 2022-10-06 16:35 UTC
**Sentry Issue:** [KAP-S85](https://sentry.io/organizations/wulkano-l0/issues/3650457242/)

**macOS version:**    Monterey (12)
**Kap version:**      3.5.5

```
Unhandled Promise Rejection

Error: ENOENT: no such file or directory, copyfile '/private/var/folders/23/76lmmmt912x596xym0ty6x8h0000gn/T/2b70211548a9665dff498de8ce93684c.mp4' -> '/Users/timo/Movies/Kaptures/Kapture 2022-10-02 at 14.33.09 B.mp4'
```

**Comment by timothyis** [comment] 2022-11-11 09:35
Duplicate of #1115

**Closed by timothyis** 2022-11-11 09:35 UTC
Labels: Sentry
