### ISSUE TITLE
MacUpdater error

### ISSUE THREAD

**Issue by steveruizok** [wulkano/Kap#1053] opened 2021-11-22 10:55 UTC
**macOS version:** 12.0 (21A344)
**Kap version:** Version 3.4.1 (3.4.1.1771)

#### Current behaviour

Every now and then, the app throws this error:

```
Unhandled Promise Rejection
Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:105:44)
```

**Comment by skllcrn** [comment] 2021-11-22 11:14
Closing as duplicate of #1046

**Closed by skllcrn** 2021-11-22 11:14 UTC
