### ISSUE TITLE
Crash at startup (apple silicon) kap 3.5.4 macOS 12.2

### ISSUE THREAD

**Issue by conphi** [wulkano/Kap#1105] opened 2022-04-01 10:11 UTC
**macOS 12.2**
**kap 3.5.4**

Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist-js/index.js:102:65

**Comment by timothyis** [comment] 2022-04-01 10:28
Duplicate of #1095

**Closed by timothyis** 2022-04-01 10:28 UTC
