### ISSUE TITLE
[UX] No clear indication whether screen is being captured or not

### ISSUE THREAD

**Issue by congp** [wulkano/kap#430] opened 2018-03-19 15:00 UTC
**Platform:**
macOS Sierra v10.12.2

**Kap Version:**
v2.0.0 (2.0.0.681)

### Steps to reproduce
Start Kap and try recording something

### Current behaviour
![screenshot 2018-03-19 08 55 08](https://user-images.githubusercontent.com/11388209/37603028-44f57236-2b53-11e8-8861-1f24de7b70cf.png)
The "Choose the area you want to capture" button and...
![screenshot 2018-03-19 08 55 14](https://user-images.githubusercontent.com/11388209/37603029-4526f266-2b53-11e8-998a-d3c25f85415a.png)
...the "Start recording" button is basically identical. Also when you start to record, there isn't a clear indication of a countdown or camera is currently rolling. 

### Expected behaviour
Bring the Crop button back please...or maybe have a clearer indicator of what the software is doing.

**Comment by albinekb** [comment] 2018-03-19 15:06
Hi!

I think this issue is a duplicate of https://github.com/wulkano/kap/issues/113

You can look at https://github.com/wulkano/kap/pull/409 which is a new design for Kap that might get incorporated.

**Comment by skllcrn** [comment] 2018-03-19 15:16
We're looking into making the cropper display immediately when opening the main app window as part of #358, so that you don't need to trigger the marquee tool. This increases the need for the crop selection to be contrasted better (#201), which @karaggeorge is working on: https://github.com/wulkano/kap/pull/409. Additionally the menubar icon animates as the recording is getting ready to start.

We haven't heard from others indicating that people have trouble knowing when Kap is recording, but we're keeping #113 open for additional feedback. I'm closing this one for now, but do chime in on the other issue(s)!

**Closed by skllcrn** 2018-03-19 15:16 UTC
