### ISSUE TITLE
No Audio in recordings longer than 10 seconds

### ISSUE THREAD

**Issue by rawcreative** [wulkano/kap#124] opened 2016-12-27 22:25 UTC
**Platform:**
OSX 10.11.6
**Kap Version:**
1.0.0.134
### Steps to reproduce
Create a screen recording including audio for longer than 10 seconds
### Current behaviour
Audio is missing in videos longer than 10 seconds. Clips under 10 seconds include audio. Multiple input sources provide the same behavior.
### Expected behaviour
Audio to be included regardless of duration
### Workaround
None

**Comment by skllcrn** [comment] 2017-01-02 13:14
I wonder if this might somehow be related to #128. Could you give us some more information about your system? RAM, OS version and anything else you think might be useful for us to know.

**Comment by rawcreative** [comment] 2017-01-04 17:41
This is happening on a Mid-15 15" i7 Macbook Pro w/ 16gb ram running El Capitan 10.11.6. ~~The only thing of note that I can think of is that it's connected to and recording the screen of an external display connected via thunderbolt~~ Just did a test without external display with the same result. This happens with or without typing or mouse interaction. 

I tested multiple times with various mic input devices, with two recordings each, both where I simply started recording and spoke (no typing or mouse movement) - one for under 10 seconds, one for over 10 seconds.

**Comment by matheuss** [comment] 2017-01-28 18:32
I can reproduce 😩 I wonder if this is somehow fixed on Sierra? (I'm on El Capitan)

**Comment by Khaledgarbaya** [comment] 2017-01-28 20:53
Hey guys Apparently this related to this issue http://stackoverflow.com/questions/26768987/avcapturesession-audio-doesnt-work-for-long-videos

**Comment by matheuss** [comment] 2017-01-28 21:54
@Khaledgarbaya I was concerned that this could be the issue 😕 We had `movieFragmentInterval` before, but we removed it since it was making the Kaptures invalid to Twitter, for example. @sindresorhus any ideas?

**Comment by sindresorhus** [comment] 2017-01-29 06:48
Ugh, I'm starting to realize just how buggy the macOS native API's are... Setting `movieFragmentInterval` to 1 second caused a semi-corrupt file. Not setting it (default 10 seconds) seems to cut off audio at that point, and setting it to invalid fixes it, but also makes the whole file corrupt if the recording does not end properly. I guess the latter is the least worst, so we can go with that if @matheuss agrees.

**Comment by Khaledgarbaya** [comment] 2017-01-29 11:54
Yeah, seems like there is no magic recipe for this, I saw some people setting it to 5 seconds, maybe before stopping the recording kap should count for the timer and gives a bit of buffer time to allow for the last fragment to be written or disable the fragment writing. I wanted to test this in aperture last night but seems like the master somehow broken. complaining about getAudioSources does not exist.

**Comment by matheuss** [comment] 2017-01-29 11:55
@sindresorhus looks like it's the best option, I'm ok with it. I wonder how QuickTime handles this 🤔

**Closed** 2017-01-31 04:20 UTC
Labels: aperture, Priority: OMG MAXIMUM, Status: Help Wanted, Type: Bug

**Comment by freelancesam** [comment] 2017-07-03 13:27
Is there a fix for this? I'm trying to record a video and getting no sound on long videos.

**Comment by CodeTheory** [comment] 2017-07-03 14:00
@freelancesam You _could_ build the app from `master` yourself but it isn't production ready so you'd have to deal with some non-styled things at the moment. I'll be working on Kap this week to we can get this fix ASAP 🤞

**Comment by matheuss** [comment] 2017-07-03 14:03
@freelancesam @CodeTheory this is fixed since the last release 🤗 See https://github.com/wulkano/kap/releases/tag/v1.0.1 👌

**Comment by CodeTheory** [comment] 2017-07-03 14:05
Ah! Wasn't aware because of the milestone labels on this issue 🙈 
@freelancesam do you have the latest release? Does it work as intended?
