### ISSUE TITLE
Doesn't working record at MacOS 12.1 (21C52)

### ISSUE THREAD

**Issue by kshirshov** [wulkano/Kap#1081] opened 2022-01-18 15:32 UTC
**macOS version:** 12.1 (21C52)
**Kap version:** Version 3.5.1 (3.5.1.1783)

#### Steps to reproduce
1. Let's open application
2. Select area: manual or window
3. Press start record 

#### Current behaviour
- Freeze UI
- Error after trying to record  

#### Expected behaviour
Recording 

#### Workaround

![image](https://user-images.githubusercontent.com/25321664/149966803-d3a9ab4d-3d76-4592-ba66-b35dcaf4d004.png)
https://user-images.githubusercontent.com/25321664/149967631-9c918806-c856-4b38-b544-76801ac83d46.mov

**Comment by timothyis** [comment] 2022-01-18 16:06
Hi there, thanks for submitting an issue. This is a duplicate of #1059, and so I will close that in order to keep track in the original issue.

**Closed by timothyis** 2022-01-18 16:06 UTC
