### ISSUE TITLE
Unhandled promise rejection on Macbook Air

### ISSUE THREAD

**Issue by Dana-111** [wulkano/Kap#1073] opened 2022-01-13 16:00 UTC
**macOS version:**    Big Sur (11)
**Kap version:**      3.4.1

#### Steps to reproduce

Do nothing, just have Kap on (not actively recording anything, the app is just on and available in the top menu)

#### Current behavior

An error appears at random times of day about some promise rejection thing

#### Expected behavior

I don't get a random error that pulls me away from whatever else I was working on at the moment

#### Workaround

Click to ignore the error. Sometimes Kap stops work after and I need to shut down the app and re-open.

Unhandled Promise Rejection
Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:105:44)

**Comment by timothyis** [comment] 2022-01-13 16:28
Hi there,

I apologise for this and thank you for submitting this. However, I believe this is a duplicate of #952 so I will close this to keep track there.

**Closed by timothyis** 2022-01-13 16:28 UTC
