### ISSUE TITLE
Marquee triggers on Skitch crosshair screenshots

### ISSUE THREAD

**Issue by onordbo** [wulkano/kap#134] opened 2017-01-27 15:49 UTC
**Platform:**
Darwin Oyvind-Nordbo.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**Kap Version:**
Version 1.0.0 (1.0.0.134)

### Steps to reproduce
1. Download and install [Skitch](https://evernote.com/skitch/)
2. Run Kap
3. Trigger Skitch crosshair screenshot `(Cmd + Shift + 5)`

### Current behaviour
Kap marquee visible while using another screenshot app.

### Expected behaviour
Kap marquee shouldn't trigger while using other apps.

### Workaround
Trigger Skitch screenshots via the menu instead of keyboard shortcut. (Doesn't trigger the marquee for some reason.)

**Comment by skllcrn** [comment] 2017-01-28 20:09
This is caused by conflicting keyboard shortcuts. The ability to customise keyboard shortcuts is planned for our next release, so that your can reassign (or remove) the key bindings to your liking!

**Comment by skllcrn** [comment] 2017-05-12 00:35
#150

**Closed** 2018-01-19 18:48 UTC
Labels: Status: Planned, Type: Enhancement
