### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alimagedayad** [wulkano/Kap#1092] opened 2022-02-08 20:01 UTC
**Sentry Issue:** [KAP-BQZ](https://sentry.io/organizations/wulkano-l0/issues/2998137097/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.5.3

```
Error

Error: Command failed with exit code 1: /Applications/Kap.app/Contents/MacOS/Kap /Applications/Kap.app/Contents/Resources/app.asar/node_modules/yarn/bin/yarn.js install --no-lockfile --registry https://registry.npmjs.org
Unknown Syntax Error: Unsupported option name ("--no-lockfile").
$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/execa/index.js:114:26)
    at async Plugins.runYarn (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/plugins/index.js:166:9)
    at async Plugins.yarnInstall (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/plugins/index.js:179:9)
    at async Plugins.install (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/plugins/index.js:51:13)
```

**Comment by timothyis** [comment] 2022-02-09 13:06
Duplicate of #1087

**Closed by timothyis** 2022-02-09 13:06 UTC
Labels: Sentry
