### ISSUE TITLE
Cannot open KAP on MacOS 12

### ISSUE THREAD

**Issue by suinntan** [wulkano/Kap#1048] opened 2021-11-11 08:13 UTC
**macOS version:12.0.1
**Kap version:Kap-3.4.2

<img width="258" alt="Screen Shot 2021-11-11 at 9 10 24 AM" src="https://user-images.githubusercontent.com/80014363/141261879-2d29d2cd-8a4b-460c-b725-75087ee1aaad.png">

**Comment by Write** [comment] 2021-11-11 18:47
Press Control key while clicking on the app.

**Comment by skllcrn** [comment] 2021-11-11 18:49
Thank you for the report, closing this as a duplicate of #1046.

**Closed by skllcrn** 2021-11-11 18:49 UTC
