### ISSUE TITLE
"Copy to clipboard" gives me a PNG, not a GIF

### ISSUE THREAD

**Issue by gingerbbm** [wulkano/kap#431] opened 2018-03-19 16:52 UTC
**Platform: Mac OS X 10.13.3 (17D102)**
**Kap Version: Version 2.0.0 (2.0.0.681)**
### Steps to reproduce
I kapture an area of the screen. Then, under "Export GIF" I choose "Copy to clipboard".
### Expected behaviour
What I expect to happen is that I end up with an animated GIF in my clipboard.
### Current behaviour
What I get is a static PNG in my clipboard.
### Workaround
None.
### Note
I did recently activate a "copy to clipboard" plugin which I assumed would automatically put it in my clipboard, so I don't know if this option was in the dropdown beforehand. Either way it's at best misleading and at worst a bit silly.

**Comment by skllcrn** [comment] 2018-03-19 16:58
This sounds like a duplicate of an issue on the repository for the plugin in question https://github.com/kevva/kap-clipboard/issues/1 

Out of curiosity, does this happen wherever you attempt to paste the content of your clipboard?

**Closed** 2018-03-19 16:59 UTC

**Comment by gingerbbm** [comment] 2018-03-19 17:02
I have tried pasting into
- HipChat (IM tool)
- Outlook (new email message)

**Comment by timothyis** [comment] 2018-03-19 17:08
Kap isn't the source of this problem. Please follow up on the issue @skllcrn posted above.
