### ISSUE TITLE
Could not get code signature for running application

### ISSUE THREAD

**Issue by lucianomlima** [wulkano/Kap#1050] opened 2021-11-11 22:14 UTC
**macOS version:** Big Sur 11.6.1
**Kap version:** 3.4.1

This appears randomly in the screen

Unhandled Promise Rejection
Error: Could not get code signature for running application
    at Server.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:105:44)

<img width="658" alt="Captura de Tela 2021-11-11 às 19 09 00" src="https://user-images.githubusercontent.com/1580205/141376429-ae0b048e-c82f-487b-ba66-f29bf5d6bcae.png">

related: #1046

**Comment by skllcrn** [comment] 2021-11-11 22:14
Closing as duplicate of #1046

**Closed by skllcrn** 2021-11-11 22:14 UTC

**Comment by skllcrn** [comment] 2021-11-11 22:16
It's the same issue, just Kap throwing the error as the updater is attempting to install in the background.

**Comment by lucianomlima** [comment] 2021-11-11 22:22
Ok! For reference, I installed via homebrew and I have already did the workaround with right-click open in context menu

**Comment by skllcrn** [comment] 2021-11-11 22:23
That makes sense, it's trying to grab 3.4.2, but that version has the same issue. Hoping to fix it over the weekend!
