### ISSUE TITLE
Error alert (could not start recording within 5 seconds)

### ISSUE THREAD

**Issue by juliankoehn** [wulkano/Kap#864] opened 2020-06-15 18:12 UTC
See Issue: #677 

`Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)`

**macOS version:**
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G13035
**Kap version:** 3.2.2.1577
#### Steps to reproduce
Install -> Start -> Record
#### Current behaviour
Crashes after 5 seconds
#### Expected behaviour
Records my Screen

**Comment by skllcrn** [comment] 2020-06-15 22:48
Thank you for the issue! Closing this as a duplicate of #854.

**Closed by skllcrn** 2020-06-15 22:48 UTC
