### ISSUE TITLE
Recording error on Mac OS X 10.10.5 when trying to record

### ISSUE THREAD

**Issue by obihill** [wulkano/kap#236] opened 2017-10-07 21:48 UTC
**Platform:** Mac OS X 10.10.5
**Kap Version:** Version 1.0.1 (1.0.1.170)

I have an issue when I use Kap to record a screencast. Whenever I click record a dialog box with the following message pops up and the recording fails:

```
**Recording Error **

fatal error: unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    main                               0x00000001085e5590 swift_reportError + 132
1    main                               0x0000000108602940 _swift_stdlib_reportFatalError + 61
2    main                               0x00000001082bc110 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 656
3    main                               0x0000000108572910 partial apply for (_fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never).(closure #2) + 109
4    main                               0x00000001082bc110 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 656
5    main                               0x000000010852d360 specialized _fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never + 96
6    main                               0x00000001082b9330 Recorder.init(destinationPath : String, fps : String, coordinates : [String], showCursor : Bool, highlightClicks : Bool, displayId : UInt32, audioDeviceId : String) throws -> Recorder + 2453
7    main                               0x00000001082ba520 Recorder.__allocating_init(destinationPath : String, fps : String, coordinates : [String], showCursor : Bool, highlightClicks : Bool, displayId : UInt32, audioDeviceId : String) throws -> Recorder + 267
8    main                               0x00000001082bd7e0 record() throws -> () + 2515
9    main                               0x00000001082bd3f0 main + 168
10   libdyld.dylib                      0x00007fff95fd35c8 start + 1
```

**Comment by CodeTheory** [comment] 2017-10-07 22:02
Hi there! Thanks for the report, however it looks like this is a duplicate of #217. I'll close this in favour of having one issue open, but thanks for confirming the issue!

**Closed by CodeTheory** 2017-10-07 22:02 UTC
